// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:arrowDownRight': typeof import('virtual:vite-icons/akar-icons/arrow-down-right')['default']
    'AkarIcons:chevronRight': typeof import('virtual:vite-icons/akar-icons/chevron-right')['default']
    'AntDesign:caretRightFilled': typeof import('virtual:vite-icons/ant-design/caret-right-filled')['default']
    'AntDesign:swapRightOutlined': typeof import('virtual:vite-icons/ant-design/swap-right-outlined')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    WhhRoadsignright: typeof import('virtual:vite-icons/whh/roadsignright')['default']
  }
}

export { }
