// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdviceSlip: typeof import('./src/components/AdviceSlip.vue')['default']
    'AkarIcons:arrowDownRight': typeof import('virtual:vite-icons/akar-icons/arrow-down-right')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppButton2: typeof import('./src/components/AppButton2.vue')['default']
    AppButton3: typeof import('./src/components/AppButton3.vue')['default']
    AppSelect: typeof import('./src/components/AppSelect.vue')['default']
    AsyncReloadPrompt: typeof import('./src/components/AsyncReloadPrompt.vue')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CommentSortByKey: typeof import('./src/components/CommentSortByKey.vue')['default']
    DataSender: typeof import('./src/components/DataSender.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ListLink: typeof import('./src/components/ListLink.vue')['default']
    ProgressButton: typeof import('./src/components/ProgressButton.vue')['default']
    ProgressButtonDemo: typeof import('./src/components/ProgressButtonDemo.vue')['default']
    Tab1: typeof import('./src/components/Tab1.vue')['default']
    Tab2: typeof import('./src/components/Tab2.vue')['default']
    TabDemo: typeof import('./src/components/TabDemo.vue')['default']
    TestParent: typeof import('./src/components/TestParent.vue')['default']
    TestParentParent: typeof import('./src/components/TestParentParent.vue')['default']
    TngInput: typeof import('./src/components/TngInput.vue')['default']
    TwitterInput: typeof import('./src/components/TwitterInput.vue')['default']
    UserCardList: typeof import('./src/components/UserCardList.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    VueLogo: typeof import('./src/components/VueLogo.vue')['default']
    W3sInput: typeof import('./src/components/w3sInput.vue')['default']
    WhhRoadsignright: typeof import('virtual:vite-icons/whh/roadsignright')['default']
  }
}

export { }
